name: build-binaries

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build release
        run: cargo build --release

      - name: Strip binary (Linux)
        if: runner.os == 'Linux'
        run: |
          # Best-effort strip to reduce artifact size
          if command -v strip >/dev/null 2>&1; then strip target/release/downloader || true; fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloader-${{ runner.os }}-${{ github.sha }}
          path: |
            target/release/downloader*
          if-no-files-found: error
          retention-days: 14
